version: "3.8"
services:
  web:
    container_name: "future_webshop_web"
    build:
      dockerfile: ./Config/Docker/Dockerfile
      context: ./
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
      - "9000:9000"
    volumes:
      - "./:/var/www/html"
    depends_on:
      - db

  db:
    container_name: "future_webshop_db"
    image: mariadb:10.6.4
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: future_webshop
      MARIADB_PASSWORD: future_webshop
      MARIADB_ROOT_PASSWORD: future_webshop
      MARIADB_DATABASE: future_webshop
